name: run_tests

on:
    pull_request:
        branches:
            - '*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 18.x

            - name: 'Run tests'
              run: |
                  npm install
                  npm run test -- --watch=false
